{
 "title": "latency",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "cpu consume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "telemetry",
     "rawSql": "SELECT\r\n  timestamp as time,\r\n  cpu\r\nFROM telemetry\r\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "telemetry",
     "rawSql": "SELECT\r\n  timestamp as time,\r\n  latency\r\nFROM telemetry\r\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "avg latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "telemetry",
     "rawSql": "SELECT\r\n  date_trunc('minute', timestamp) as time,\r\n  avg(latency)\r\nFROM telemetry\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "players online",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "telemetry",
     "rawSql": "SELECT\r\n  timestamp as time,\r\n  players\r\nFROM telemetry\r\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "players online now",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "telemetry",
     "rawSql": "SELECT players\r\nFROM telemetry\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  }
 ]
}